### ISSUE TITLE
如何不进行lint检查？

### ISSUE THREAD

**Issue by caiql** [wangbin3162/bin-ace-editor#25]
有时候有红色的交叉，很难看，有没有什么属性可以取消检查

**Comment by wangbin3162** [comment]
代码中尝试过好像不可以关闭lint，但可以在组件引入时不导入这个插件试试
![image](https://user-images.githubusercontent.com/33084011/129533866-523a6d21-1db5-4e37-b94f-491e9371d2fe.png)
