### ISSUE TITLE
文档有误，影响使用

### ISSUE THREAD

**Issue by milkiq** [wangbin3162/bin-ace-editor#28]
组件不支持 v-model ，而且传入值的 prop 不是 value，是 modelValue 。

对于双向绑定，实际支持的是 v-bind:model-value.sync 。

**Comment by hansonfang** [comment]
+1

**Comment by wangbin3162** [comment]
具体请参考文档说明，modelValue为的是适配vue3版本，vue2版本，请锁定版本号进行安装即可
