### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Claiyre** [wangbin3162/bin-ace-editor#34]
### 环境
"bin-ace-editor": "^3.1.1",
"element-plus": "^1.0.2-beta.42",
"vue": "^3.0.5"
使用vite脚手架创建，vue3 + typescript

### 使用方式
![image](https://user-images.githubusercontent.com/18069718/130569995-3147af10-9432-45df-bcfa-69ec7bfc43c1.png)

### 报错截图

![image](https://user-images.githubusercontent.com/18069718/130569996-f5d77a02-e23b-4960-9768-7833ec46a9b4.png)

**Comment by wangbin3162** [comment]
![image](https://user-images.githubusercontent.com/33084011/131994172-0998ba24-d7db-428d-bee1-61a7bf924f11.png)
在vite中使用时，需要在此配置里填写brace即可

**Comment by wangbin3162** [comment]
您好，因版本控制问题，vue3版本现已迁移至bin-editor-next这个包，重新安装一下bin-editor-next即可，组件名称和使用和旧版本一样

**Comment by hellodigua** [comment]
> ![image](https://user-images.githubusercontent.com/33084011/131994172-0998ba24-d7db-428d-bee1-61a7bf924f11.png) 在vite中使用时，需要在此配置里填写brace即可

使用新版编辑器`bin-editor-next` 时也会遇到 module is not defined 这个问题，建议把这部分说明在新版编辑器的文档中说明一下
