### ISSUE TITLE
Uncaught ReferenceError: require is not defined     at index.vue:6 (anonymous) @ index.vue:6

### ISSUE THREAD

**Issue by zzz2018** [wangbin3162/bin-ace-editor#40]
![image](https://user-images.githubusercontent.com/30309686/132798270-841e4ff1-a5f6-431f-a1e6-da3aa6bbf1e1.png)
![image](https://user-images.githubusercontent.com/30309686/132798423-f53b5cb7-64f9-4fb2-a310-191924c1b7e9.png)

使用版本：vue3.2.11 + vite 2.5.6 + 3.2.0

vite已加
![image](https://user-images.githubusercontent.com/30309686/132798442-77a50a40-8541-4c9c-ab27-641c8bf9afdb.png)

**Comment by wangbin3162** [comment]
vue3版本请使用bin-editor-next，现在已迁移至这个包
