### ISSUE TITLE
请求大佬支援！

### ISSUE THREAD

**Issue by ddumaike** [wangbin3162/bin-ace-editor#5]
用过一些JSON编辑器，最喜欢大佬提供的这个，大赞！！！
大佬能否多撸上以下2个功能：
1.自适应JSON内容高度（readonly模式）
2.复制JSON数据功能
PS：用过vue-json-viewer(https://www.npmjs.com/package/vue-json-viewer)
以上两个功能用起来感觉比较舒服，不过点击下拉收起的按钮样式实在有点丑，所以打算以后使用bin-ace-editor了，望大佬支援一波，感谢！

**Comment by wangbin3162** [comment]
自适应功能较为复杂，需要额外判断输入内容的高度再去计算，不同的皮肤字体可能高度也不同，所以暂不考虑加此功能了，至于复制json，可以自己加一个按钮自定义实现，不属于这个组件的功能范畴了
